# Generated by Django 3.1.7 on 2021-03-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suphome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='tag',
            field=models.IntegerField(default=0),
        ),
    ]
